const fs=require('fs');
const path=require('path');
const file=path.join(__dirname,'dist','admin.html');
if(!fs.existsSync(file))throw new Error('dist/admin.html não encontrado');
let html=fs.readFileSync(file,'utf8');
const style=`<style id="mythos-cargos-style">
.roleCard{border:1px solid #3a1d4b;border-radius:16px;background:linear-gradient(145deg,#100817,#090b12);padding:14px;margin:10px 0;box-shadow:0 0 22px rgba(146,48,255,.08)}
.roleCard h3{margin:0 0 5px}.rolePerm{color:#aaa0b0;font-size:11px;line-height:1.6}.roleTag{display:inline-block;padding:5px 8px;border-radius:999px;background:#21102b;color:#24e3f4;font-size:9px;font-weight:900;margin:3px}
.cargoSelect{width:100%;padding:13px;background:#09050e;border:1px solid #4a235d;border-radius:12px;color:#fff;font-size:14px}.cargoSelect:focus{outline:none;border-color:#b43cff;box-shadow:0 0 16px rgba(180,60,255,.22)}
.cargoActions{display:flex;gap:10px;margin-top:10px}.cargoSave{border:0;border-radius:13px;padding:12px 18px;font-weight:900;background:linear-gradient(90deg,#8b2cff,#20d9ff);color:#09050e;cursor:pointer}.cargoSave:disabled{opacity:.55;cursor:default}
.cargoModal{position:fixed;inset:0;z-index:99999;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(2,1,7,.76);backdrop-filter:blur(14px)}
.cargoModal.open{display:flex}.cargoDialog{width:min(620px,100%);max-height:90vh;overflow:auto;border:1px solid #3d3150;border-radius:28px;background:linear-gradient(145deg,#11111b,#080911);box-shadow:0 0 60px rgba(174,52,255,.25);padding:22px}.cargoHead{display:flex;align-items:center;gap:14px;margin-bottom:16px}.cargoIcon{width:52px;height:52px;border-radius:18px;display:grid;place-items:center;background:linear-gradient(135deg,#7d20ff,#14d9ff);font-size:27px}.cargoHead h2{margin:0}.cargoHead p{margin:4px 0 0;color:#aaa}.cargoClose{margin-left:auto;border:1px solid #333344;background:#171722;color:#fff;width:44px;height:44px;border-radius:50%;font-size:25px;cursor:pointer}
.cargoOption{display:flex;align-items:center;gap:13px;padding:14px;margin:8px 0;border:1px solid #262535;border-radius:17px;background:#10111a;cursor:pointer;transition:.18s}.cargoOption:hover{border-color:#67338a;transform:translateY(-1px)}.cargoOption.selected{border-color:#c13cff;background:linear-gradient(90deg,rgba(140,38,255,.18),rgba(22,214,255,.05));box-shadow:0 0 20px rgba(193,60,255,.12)}.cargoRoleIcon{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#20202d;font-size:20px;flex:none}.cargoOption b{display:block;font-size:14px}.cargoOption small{display:block;color:#a9a5b2;margin-top:3px}.cargoRadio{margin-left:auto;width:23px;height:23px;border:2px solid #858894;border-radius:50%;display:grid;place-items:center;flex:none}.cargoOption.selected .cargoRadio{border-color:#c33cff;box-shadow:0 0 12px rgba(195,60,255,.6)}.cargoOption.selected .cargoRadio:after{content:'';width:11px;height:11px;border-radius:50%;background:#c33cff}
.cargoFooter{display:flex;gap:12px;margin-top:16px}.cargoCancel,.cargoConfirm{flex:1;padding:14px;border-radius:14px;font-weight:900;cursor:pointer}.cargoCancel{border:1px solid #30313d;background:#191a24;color:#ddd}.cargoConfirm{border:0;background:linear-gradient(90deg,#8d2cff,#20d9ff);color:#09050e}.cargoNote{text-align:center;color:#a9a5b2;font-size:12px;margin-top:12px}.cargoMsg{margin-top:10px}
@media(max-width:600px){.cargoDialog{border-radius:24px;padding:16px}.cargoFooter{position:sticky;bottom:0;background:#090911;padding-top:10px}.cargoOption{padding:12px}}
</style>`;
const script=`<script id="mythos-cargos-script">(()=>{
const labels={owner:'Owner',staff:'Staff',all:'ALL',manager:'Manager',admin_lider:'Admin Líder',admin_2:'Admin 2',sublider:'Sublíder',suporte:'Suporte',admin_assistente:'Admin Assistente',atendimento:'Atendimento',developer:'Developer',player:'Player'};
const descriptions={player:'Usuário comum da comunidade.',suporte:'Atendimento e suporte aos usuários.',staff:'Auxílio na administração e eventos.',manager:'Gerenciamento de equipes.',admin_lider:'Administração avançada.',admin_2:'Administração operacional.',sublider:'Apoio à liderança.',admin_assistente:'Assistência administrativa.',atendimento:'Atendimento de tickets.',developer:'Desenvolvimento e manutenção.',all:'Acesso administrativo ampliado.',owner:'Acesso total ao sistema.'};
const icons={player:'●',suporte:'●●●',staff:'◆',manager:'⚙',admin_lider:'★',admin_2:'◆',sublider:'◇',admin_assistente:'+',atendimento:'?',developer:'</>',all:'✦',owner:'♛'};
const full=['owner','staff','all'];const allowed=['owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','admin_assistente','atendimento','developer','player'];
let selectedUser=null,selectedRole='player';
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function isOwner(){return String(window.__mythosRole||'')==='owner';}
window.login=async function(){try{const r=await fetch('/api/auth?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('email').value,password:document.getElementById('password').value})});const j=await r.json();if(!r.ok)throw Error(j.error||'Falha no login');if(!allowed.includes(j.user.role))throw Error('Este cargo não possui acesso ao painel.');localStorage.setItem('mythos_admin_token',j.token);window.__mythosRole=j.user.role;window.show();}catch(e){const m=document.getElementById('loginMsg');m.className='msg err';m.textContent=e.message}};
function inject(){if(document.getElementById('cargos'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;const b=document.createElement('button');b.className='tab';b.textContent='CARGOS';b.onclick=()=>window.tab('cargos',b);tabs.appendChild(b);const sec=document.createElement('section');sec.id='cargos';sec.className='panel';sec.innerHTML='<div class="box"><div class="head"><div><h2>CARGOS E PERMISSÕES</h2><div class="muted">Controle de acesso do painel administrativo.</div></div><button class="btn" onclick="window.loadCargos()">ATUALIZAR</button></div><div class="hint"><b>Owner</b>: acesso total e pode conceder o cargo Owner. Staff e ALL possuem acesso administrativo conforme suas permissões.</div><div id="cargoRoles" class="permGrid" style="margin:12px 0"></div><div id="cargoMembers">Carregando...</div><div id="cargoMsg" class="msg"></div></div>';document.getElementById('adminBox').appendChild(sec);createModal()}
function createModal(){if(document.getElementById('cargoModal'))return;const m=document.createElement('div');m.id='cargoModal';m.className='cargoModal';m.innerHTML='<div class="cargoDialog" role="dialog" aria-modal="true"><div class="cargoHead"><div class="cargoIcon">♛</div><div><h2>Selecionar Cargo</h2><p>Escolha o cargo que deseja definir para o usuário.</p></div><button class="cargoClose" onclick="window.closeCargoModal()">×</button></div><div id="cargoOptions"></div><div id="cargoModalMsg" class="cargoMsg"></div><div class="cargoFooter"><button class="cargoCancel" onclick="window.closeCargoModal()">CANCELAR</button><button class="cargoConfirm" onclick="window.confirmCargo()">CONFIRMAR</button></div><div class="cargoNote">ⓘ Somente Owners podem conceder o cargo de Owner.</div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)window.closeCargoModal()})}
function openModal(u){createModal();selectedUser=u;selectedRole=u.role||'player';renderOptions();document.getElementById('cargoModal').classList.add('open')}
function renderOptions(){const box=document.getElementById('cargoOptions');box.innerHTML=Object.keys(labels).map(r=>'<div class="cargoOption '+(r===selectedRole?'selected':'')+'" data-role="'+r+'"><div class="cargoRoleIcon">'+icons[r]+'</div><div><b>'+labels[r]+'</b><small>'+descriptions[r]+'</small></div><div class="cargoRadio"></div></div>').join('');box.querySelectorAll('.cargoOption').forEach(o=>o.onclick=()=>{selectedRole=o.dataset.role;renderOptions()})}
window.closeCargoModal=()=>document.getElementById('cargoModal')?.classList.remove('open');
window.confirmCargo=async()=>{if(!selectedUser)return;const msg=document.getElementById('cargoModalMsg');msg.className='cargoMsg';msg.textContent='Salvando...';try{const r=await fetch('/api/db?table=users',{method:'PATCH',headers:{Authorization:'Bearer '+localStorage.getItem('mythos_admin_token'),'Content-Type':'application/json'},body:JSON.stringify({id:selectedUser.id,role:selectedRole})});const j=await r.json();if(!r.ok)throw Error(j.error||'Erro ao atualizar cargo');window.closeCargoModal();document.getElementById('cargoMsg').className='msg';document.getElementById('cargoMsg').textContent='Cargo atualizado com sucesso.';await window.loadCargos()}catch(e){msg.className='cargoMsg msg err';msg.textContent=e.message}};
function filterTabs(){const role=window.__mythosRole||'';const all=full.includes(role)||role==='owner';document.querySelectorAll('.tabs .tab').forEach(b=>{const t=b.textContent.trim();if(t==='CARGOS'||t==='MEMBROS')b.style.display=all?'':'none';if(t==='LOGS')b.style.display=(all||['manager','admin_lider'].includes(role))?'':'none';if(t==='TICKETS')b.style.display=(all||['suporte','atendimento'].includes(role))?'':'none';if(t==='CARTÃO PONTO')b.style.display=(all||['manager','admin_lider','admin_2','sublider','suporte','admin_assistente','atendimento'].includes(role))?'':'none';})}
window.loadCargos=async()=>{inject();createModal();const box=document.getElementById('cargoMembers');try{const r=await fetch('/api/db?table=users',{headers:{Authorization:'Bearer '+localStorage.getItem('mythos_admin_token')}});const j=await r.json();if(!r.ok)throw Error(j.error||'Sem permissão');document.getElementById('cargoRoles').innerHTML=Object.keys(labels).filter(x=>x!=='player').map(x=>'<div class="roleCard"><h3>'+labels[x]+'</h3><div class="rolePerm">'+(x==='owner'?'Acesso total ao sistema.':descriptions[x])+'</div></div>').join('');box.innerHTML=j.users.map(u=>{const protectedUser=String(u.email||'').toLowerCase()==='quenidyyonline.17@gmail.com'||String(u.email||'').toLowerCase()==='gamesfloriano8@gmail.com';return '<div class="user"><div class="avatar">'+esc(String(u.display_name||'?').slice(0,1).toUpperCase())+'</div><div><strong>'+esc(u.display_name||u.email)+'</strong><small>'+esc(u.email||'')+'</small></div><div class="roleBox"><select class="cargoSelect" data-id="'+esc(u.id)+'" style="display:none"><option>'+esc(u.role||'player')+'</option></select><button class="cargoSave" type="button">'+esc(labels[u.role||'player'])+' · ALTERAR CARGO</button><div class="rolePerm">Atual: <b>'+esc(labels[u.role||'player']||u.role||'player')+'</b>'+(protectedUser?' · OWNER PROTEGIDO':'')+'</div></div></div>'}).join('');box.querySelectorAll('.cargoSave').forEach((btn,i)=>{const u=j.users[i];const protectedUser=String(u.email||'').toLowerCase()==='quenidyyonline.17@gmail.com'||String(u.email||'').toLowerCase()==='gamesfloriano8@gmail.com';btn.disabled=protectedUser;btn.onclick=()=>openModal(u)});}catch(e){box.innerHTML='<div class="msg err">'+esc(e.message)+'</div>'}};
const oldShow=window.show;window.show=async function(){document.getElementById('loginBox').classList.add('hidden');document.getElementById('adminBox').classList.remove('hidden');filterTabs();inject();try{if(typeof window.loadSettings==='function')await window.loadSettings()}catch{}if(full.includes(window.__mythosRole)||window.__mythosRole==='owner'){try{await window.loadMembers()}catch{}try{await window.loadTickets()}catch{}try{await window.loadLogs()}catch{}try{await window.loadCargos()}catch{}}};
setTimeout(()=>{inject();const t=localStorage.getItem('mythos_admin_token');if(t)fetch('/api/auth?action=me',{headers:{Authorization:'Bearer '+t}}).then(r=>r.json()).then(j=>{if(j.user&&allowed.includes(j.user.role)){window.__mythosRole=j.user.role;window.show()}}).catch(()=>{})},300);
})();</script>`;
html=html.replace(/<style id="mythos-cargos-style">[\s\S]*?<\/style>/,'');
html=html.replace(/<script id="mythos-cargos-script">[\s\S]*?<\/script>/,'');
html=html.replace('</head>',style+'</head>');
html=html.replace('</body>',script+'</body>');
fs.writeFileSync(file,html);console.log('Cargo panel generated.');
