const fs=require('fs');
const path=require('path');
const file=path.join(__dirname,'dist','admin.html');
if(!fs.existsSync(file))throw new Error('dist/admin.html não encontrado');
let html=fs.readFileSync(file,'utf8');
const style=`<style id="mythos-cargos-style">.roleCard{border:1px solid #3a1d4b;border-radius:14px;background:#0d0712;padding:14px;margin:10px 0}.roleCard h3{margin:0 0 5px}.rolePerm{color:#aaa0b0;font-size:11px;line-height:1.6}.roleTag{display:inline-block;padding:5px 8px;border-radius:999px;background:#21102b;color:#24e3f4;font-size:9px;font-weight:900;margin-right:5px}.cargoSelect{width:100%;padding:11px;background:#09050e;border:1px solid #4a235d;border-radius:10px;color:#fff}.permGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}@media(max-width:600px){.permGrid{grid-template-columns:1fr}}</style>`;
const script=`<script id="mythos-cargos-script">(()=>{const labels={owner:'Owner',staff:'Staff',all:'ALL',manager:'Manager',admin_lider:'Admin Líder',admin_2:'Admin 2',sublider:'Sublíder',suporte:'Suporte',atendimento:'Atendimento',player:'Player'};const perms={owner:['Acesso a tudo'],staff:['Acesso a tudo'],all:['Acesso a tudo'],manager:['Logs','Auditoria','Ponto','Justificativa'],admin_lider:['Logs','Ponto','Justificativa'],admin_2:['Ponto','Justificativa'],sublider:['Ponto','Justificativa'],suporte:['Atendimento / Tickets','Ponto','Justificativa'],atendimento:['Tickets','Ponto','Justificativa'],player:[]};const options=Object.keys(labels).map(r=>'<option value="'+r+'">'+labels[r]+'</option>').join('');
async function cargoLogin(){try{const r=await fetch('/api/auth?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('email').value,password:document.getElementById('password').value})});const j=await r.json();if(!r.ok)throw Error(j.error||'Falha no login');const allowed=['owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','atendimento'];if(!allowed.includes(j.user.role))throw Error('Este cargo não possui acesso ao painel.');localStorage.setItem('mythos_admin_token',j.token);window.show();}catch(e){const m=document.getElementById('loginMsg');m.className='msg err';m.textContent=e.message}}
window.login=cargoLogin;
function inject(){if(document.getElementById('cargos'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;const b=document.createElement('button');b.className='tab';b.textContent='CARGOS';b.onclick=()=>window.tab('cargos',b);tabs.appendChild(b);const sec=document.createElement('section');sec.id='cargos';sec.className='panel';sec.innerHTML='<div class="box"><div class="head"><div><h2>CARGOS E PERMISSÕES</h2><div class="muted">Controle de acesso do painel administrativo.</div></div><button class="btn" onclick="window.loadCargos()">ATUALIZAR</button></div><div class="hint"><b>Owner</b>, <b>Staff</b> e <b>ALL</b>: acesso total. Os demais cargos recebem somente as permissões abaixo.</div><div id="cargoRoles" class="permGrid" style="margin:12px 0"></div><div id="cargoMembers">Carregando...</div><div id="cargoMsg" class="msg"></div></div>';document.getElementById('adminBox').appendChild(sec)}
function filterTabs(){const role=window.__mythosRole;const all=['owner','staff','all'].includes(role);document.querySelectorAll('.tabs .tab').forEach(b=>{const t=b.textContent.trim();if(t==='CARGOS'||t==='MEMBROS')b.style.display=all?'':'none';if(t==='LOGS')b.style.display=(all||['manager','admin_lider'].includes(role))?'':'none';if(t==='TICKETS')b.style.display=(all||['suporte','atendimento'].includes(role))?'':'none';if(t==='CARTÃO PONTO')b.style.display=(all||['manager','admin_lider','admin_2','sublider','suporte','atendimento'].includes(role))?'':'none';});}
window.loadCargos=async()=>{inject();const box=document.getElementById('cargoMembers');try{const r=await fetch('/api/db?table=users',{headers:{Authorization:'Bearer '+localStorage.getItem('mythos_admin_token')}});const j=await r.json();if(!r.ok)throw Error(j.error||'Sem permissão');document.getElementById('cargoRoles').innerHTML=Object.keys(labels).filter(x=>x!=='player').map(x=>'<div class="roleCard"><h3>'+labels[x]+'</h3><div class="rolePerm">'+perms[x].map(p=>'<span class="roleTag">'+p+'</span>').join('')+'</div></div>').join('');box.innerHTML=j.users.map(u=>'<div class="user"><div class="avatar">'+String(u.display_name||'?').slice(0,1).toUpperCase()+'</div><div><strong>'+String(u.display_name||u.email)+'</strong><small>'+String(u.email||'')+'</small></div><div class="roleBox"><select class="cargoSelect" data-id="'+u.id+'">'+options.replace('value="'+(u.role||'player')+'"','value="'+(u.role||'player')+'" selected')+'</select><div class="rolePerm">Atual: <b>'+labels[u.role||'player']+'</b></div></div></div>').join('');box.querySelectorAll('.cargoSelect').forEach(s=>s.addEventListener('change',async()=>{try{const r=await fetch('/api/db?table=users',{method:'PATCH',headers:{Authorization:'Bearer '+localStorage.getItem('mythos_admin_token'),'Content-Type':'application/json'},body:JSON.stringify({id:s.dataset.id,role:s.value})});const j=await r.json();if(!r.ok)throw Error(j.error||'Erro');document.getElementById('cargoMsg').textContent='Cargo atualizado com sucesso.';loadCargos()}catch(e){document.getElementById('cargoMsg').className='msg err';document.getElementById('cargoMsg').textContent=e.message}}));}catch(e){box.textContent=e.message}};
const oldShow=window.show;window.show=async function(){await oldShow();try{const r=await fetch('/api/auth?action=me',{headers:{Authorization:'Bearer '+localStorage.getItem('mythos_admin_token')}});const j=await r.json();window.__mythosRole=j.user?.role||'';filterTabs();inject()}catch{inject()}};setTimeout(inject,300);})();</script>`;
html=html.replace('</head>',style+'</head>');html=html.replace('</body>',script+'</body>');fs.writeFileSync(file,html);console.log('Cargo panel generated.');
