const fs=require('fs');
const path=require('path');
require('./build');
const root=__dirname;
const rulesPath=path.join(root,'dist','regras.html');
const sourcePath=path.join(root,'src','data','mythos-rules.ts');
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const baseCss=`<style>*{box-sizing:border-box}html{background:#050507}body{margin:0;background:radial-gradient(circle at 50% 0,#17101f 0,#08070b 35%,#050507 75%);color:#f7f5fb;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{width:min(900px,100%);margin:auto;padding:14px}.top{position:sticky;top:0;z-index:20;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;background:#050507ed;backdrop-filter:blur(14px);border-bottom:1px solid #292431}.logo{font-size:19px;font-weight:950}.grad{background:linear-gradient(90deg,#18d9ff,#a83cff,#ff18d0);-webkit-background-clip:text;color:transparent}.back{color:#20ddf5;text-decoration:none;font-size:11px;font-weight:900}.hero{padding:30px 0 22px}.eyebrow{color:#16def4;font-size:10px;font-weight:900;letter-spacing:2px}.hero h1{font-size:clamp(34px,7vw,60px);line-height:1;margin:15px 0 10px}.hero p{color:#9995a5;line-height:1.65;margin:0}.list{display:grid;gap:10px}.link{display:block;padding:17px 18px;border:1px solid #3b3046;border-radius:14px;background:#0b0910;text-decoration:none;color:#fff}.link strong{display:block;font-size:14px}.link span{display:block;color:#817b8b;font-size:11px;margin-top:5px}.embed{position:relative;margin:12px 0;padding:16px 17px 17px 19px;border:1px solid #30283a;border-radius:12px;background:linear-gradient(180deg,#0e0b13,#0a080e);box-shadow:0 8px 25px #0005;overflow:hidden}.embed:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:linear-gradient(180deg,#18d9ff,#a83cff,#ff18d0)}.embedNo{font-size:10px;color:#8f899b;font-weight:900;letter-spacing:.5px;margin-bottom:7px}.embedText{font-size:13px;line-height:1.75;color:#dedbe4;white-space:pre-line;overflow-wrap:anywhere}.count{color:#16def4;font-size:10px;font-weight:900}.footer{border-top:1px solid #1c1921;margin-top:34px;padding:28px 0 50px;color:#65616d;font-size:11px}@media(max-width:480px){.wrap{padding:11px}.embed{padding:15px 14px 16px 17px}.embedText{font-size:12.5px}}</style>`;
function parseRules(){if(!fs.existsSync(sourcePath))return[];const source=fs.readFileSync(sourcePath,'utf8');const match=source.match(/export const MYTHOS_RULES[^=]*=\s*(\[[\s\S]*?\]);/);if(!match)return[];try{return Function('return '+match[1])()}catch(e){console.error('rules parse failed',e);return[]}}
function pageShell(title,body,script=''){return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050507"><title>'+esc(title)+'</title>'+baseCss+'</head><body><main class="wrap">'+body+'</main>'+script+'</body></html>'}
const data=parseRules();
if(data.length){
 let index='<header class="top"><div class="logo">REDE <span class="grad">MYTHØS</span></div><a class="back" href="/">← VOLTAR</a></header><section class="hero"><span class="eyebrow">MYTHØS · REGULAMENTO OFICIAL</span><h1>Central de <span class="grad">Regras</span></h1><p>As regras ficam separadas por página. Cada categoria abre em sua própria página, com cada regra apresentada em formato de embed para manter o texto legível e completo.</p></section><div class="list">';
 data.forEach((r,i)=>{index+='<a class="link" href="/regras-'+(i+1)+'.html"><strong>'+esc(r.number+'. '+r.title)+'</strong><span>'+r.items.length+' itens · Abrir página completa →</span></a>'});
 index+='</div><footer class="footer">MYTHØS NETWORK • Regulamento Oficial</footer>';
 fs.writeFileSync(rulesPath,pageShell('Mythøs • Central de Regras',index));
 data.forEach((r,i)=>{
   const items=r.items.map((x,j)=>'<article class="embed"><div class="embedNo">ITEM '+String(j+1).padStart(3,'0')+'</div><div class="embedText">'+esc(x)+'</div></article>').join('');
   const body='<header class="top"><div class="logo">REDE <span class="grad">MYTHØS</span></div><a class="back" href="/regras.html">← REGRAS</a></header><section class="hero"><span class="eyebrow">MYTHØS · REGULAMENTO OFICIAL</span><h1>'+esc(r.title)+'</h1><p><span class="count">'+r.items.length+' itens</span> · conteúdo integral desta seção.</p></section><section id="rules">'+items+'</section><footer class="footer">MYTHØS NETWORK • <a class="back" href="/regras.html">Voltar para a Central</a></footer>';
   const script='<script>(async()=>{try{const wanted='+i+';const r=await fetch("/api/rules",{cache:"no-store"}),j=await r.json();if(!r.ok||!Array.isArray(j.rules)||!j.rules[wanted])return;const s=j.rules[wanted];document.querySelector("h1").textContent=String(s.number||"")+". "+String(s.title||"");document.querySelector(".hero p").innerHTML="<span class=\"count\">"+s.items.length+" itens</span> · conteúdo integral desta seção.";document.getElementById("rules").innerHTML=s.items.map((x,k)=>`<article class="embed"><div class="embedNo">ITEM ${String(k+1).padStart(3,"0")}</div><div class="embedText">${String(x).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}</div></article>`).join("")}catch(e){}})();</script>';
   fs.writeFileSync(path.join(root,'dist','regras-'+(i+1)+'.html'),pageShell('Mythøs • '+r.title,body,script));
 });
}
const adminPath=path.join(root,'dist','admin.html');
const editorPath=path.join(root,'dist','regras-admin.js');
if(fs.existsSync(adminPath)&&fs.existsSync(editorPath)){let a=fs.readFileSync(adminPath,'utf8');if(!a.includes('regras-admin.js')){a=a.replace('</body>','<script src="/regras-admin.js"></script></body>');fs.writeFileSync(adminPath,a)}}
console.log('Full build: separate rule pages + embed layout + live admin rules.');
