const fs=require('fs');
const path=require('path');
require('./build');
const root=__dirname;
const rulesPath=path.join(root,'dist','regras.html');
const sourcePath=path.join(root,'src','data','mythos-rules.ts');
if(fs.existsSync(rulesPath)&&fs.existsSync(sourcePath)){
 const source=fs.readFileSync(sourcePath,'utf8');
 const match=source.match(/export const MYTHOS_RULES[^=]*=\s*(\[[\s\S]*?\]);/);
 if(match){let data;try{data=Function('return '+match[1])()}catch(e){console.error('rules parse failed',e);process.exit(1)}
 const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const css=`<style>body{background:#050507;color:#fff;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{width:min(1100px,100%);margin:auto;padding:18px}.top{position:sticky;top:0;z-index:10;display:flex;justify-content:space-between;padding:14px 0;background:#050507ee;border-bottom:1px solid #20202a}.logo{font-size:22px;font-weight:950}.grad{background:linear-gradient(90deg,#18d9ff,#a83cff,#ff18d0);-webkit-background-clip:text;color:transparent}.back{color:#20ddf5;text-decoration:none}.hero{padding:34px 0}.eyebrow{color:#16def4;font-size:10px;font-weight:900;letter-spacing:2px}.hero h1{font-size:clamp(40px,8vw,72px);margin:18px 0 10px}.hero p{color:#9895a1;line-height:1.7}.index{display:flex;flex-wrap:wrap;gap:8px}.index a{padding:10px 12px;border:1px solid #2b2935;border-radius:10px;background:#0c0c11;color:#ddd;text-decoration:none;font-weight:850;font-size:12px}.category{margin:32px 0 44px;scroll-margin-top:85px}.category h2{font-size:28px;margin-bottom:14px}.chapter{margin:18px 0;padding:0;background:transparent;border:0;overflow:visible}.chapter h3{margin:0;padding:0 0 10px;background:transparent;border:0;font-size:14px;color:#16def4;text-transform:uppercase;letter-spacing:1px}.chapter ul{margin:0;padding:0;list-style:none}.chapter li{padding:13px 0;border-bottom:1px solid #191820;color:#d7d5dd;font-size:14px;line-height:1.8;white-space:pre-line;overflow:visible;overflow-wrap:anywhere}.chapter li:last-child{border-bottom:0}.count{float:right;color:#16def4;font-size:10px}.footer{border-top:1px solid #1a1920;padding:30px 0 50px;color:#66636f;font-size:11px}@media(max-width:760px){.wrap{padding:12px}.category h2{font-size:22px}.chapter li{font-size:14px;line-height:1.85}}@media(max-width:420px){.index{gap:6px}.index a{font-size:11px}}</style>`;
 let out='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050507"><title>Mythøs • Central de Regras</title>'+css+'</head><body><main class="wrap"><header class="top"><div class="logo">REDE <span class="grad">MYTHØS</span></div><a class="back" href="/">← VOLTAR AO SITE</a></header><section class="hero"><span class="eyebrow">MYTHØS · REGULAMENTO OFICIAL</span><h1>Central de <span class="grad">Regras</span></h1><p>Regulamento oficial da comunidade, com o texto completo disponível para leitura e edição administrativa.</p></section><nav class="index">'+data.map((r,i)=>'<a href="#cat-'+i+'">'+esc(r.number+'. '+r.title)+'</a>').join('')+'</nav>';
 for(let i=0;i<data.length;i++){const r=data[i];out+='<section class="category" id="cat-'+i+'"><h2>'+esc(r.number+'. '+r.title)+' <span class="count">'+r.items.length+' itens</span></h2><article class="chapter"><h3>Conteúdo integral</h3><ul>'+r.items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></article></section>';}
 out+='<footer class="footer">MYTHØS NETWORK • Regulamento Oficial</footer></main><script>(async()=>{try{const r=await fetch("/api/rules",{cache:"no-store"}),j=await r.json();if(!r.ok||!Array.isArray(j.rules))return;const data=j.rules;const nav=document.querySelector(".index");const main=document.querySelector("main");if(!nav||!main)return;nav.innerHTML=data.map((x,i)=>`<a href="#cat-${i}">${String(x.number)}. ${String(x.title)}</a>`).join("");main.querySelectorAll(".category").forEach(x=>x.remove());const f=main.querySelector(".footer");data.forEach((x,i)=>{const s=document.createElement("section");s.className="category";s.id="cat-"+i;s.innerHTML=`<h2>${String(x.number)}. ${String(x.title)} <span class="count">${x.items.length} itens</span></h2><article class="chapter"><h3>Conteúdo integral</h3><ul>${x.items.map(v=>`<li>${String(v).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}</li>`).join("")}</ul></article></section>`;main.insertBefore(s,f)})}catch(e){}})();</script></body></html>';
 fs.writeFileSync(rulesPath,out);
 }}
const adminPath=path.join(root,'dist','admin.html');
const editorPath=path.join(root,'dist','regras-admin.js');
if(fs.existsSync(adminPath)&&fs.existsSync(editorPath)){let a=fs.readFileSync(adminPath,'utf8');if(!a.includes('regras-admin.js')){a=a.replace('</body>','<script src="/regras-admin.js"></script></body>');fs.writeFileSync(adminPath,a)}}
console.log('Full build: rules rendered as unrestricted full-text sections + live admin editor.');
