const fs=require('fs');
const path=require('path');
const dist=path.join(__dirname,'dist');
if(!fs.existsSync(dist))fs.mkdirSync(dist,{recursive:true});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`<style>*{box-sizing:border-box}html{background:#050507}body{margin:0;background:radial-gradient(circle at 50% 0,#17101f 0,#08070b 35%,#050507 75%);color:#f7f5fb;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{width:min(900px,100%);margin:auto;padding:14px}.top{position:sticky;top:0;z-index:20;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;background:#050507ed;backdrop-filter:blur(14px);border-bottom:1px solid #292431}.logo{font-size:19px;font-weight:950}.grad{background:linear-gradient(90deg,#18d9ff,#a83cff,#ff18d0);-webkit-background-clip:text;color:transparent}.back{color:#20ddf5;text-decoration:none;font-size:11px;font-weight:900}.hero{padding:30px 0 22px}.eyebrow{color:#16def4;font-size:10px;font-weight:900;letter-spacing:2px}.hero h1{font-size:clamp(30px,7vw,56px);line-height:1;margin:15px 0 10px}.hero p{color:#9995a5;line-height:1.65;margin:0}.embed{position:relative;margin:12px 0;padding:16px 17px 17px 19px;border:1px solid #30283a;border-radius:12px;background:linear-gradient(180deg,#0e0b13,#0a080e);box-shadow:0 8px 25px #0005;overflow:hidden}.embed:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:linear-gradient(180deg,#18d9ff,#a83cff,#ff18d0)}.embedNo{font-size:10px;color:#8f899b;font-weight:900;letter-spacing:.5px;margin-bottom:7px}.embedText{font-size:13px;line-height:1.75;color:#dedbe4;white-space:pre-line;overflow-wrap:anywhere}.footer{border-top:1px solid #1c1921;margin-top:34px;padding:28px 0 50px;color:#65616d;font-size:11px}@media(max-width:480px){.wrap{padding:11px}.embed{padding:15px 14px 16px 17px}.embedText{font-size:12.5px}}</style>`;
const html='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050507"><title>Mythøs • Regras da Polícia</title>'+css+'</head><body><main class="wrap"><header class="top"><div class="logo">REDE <span class="grad">MYTHØS</span></div><a class="back" href="/regras.html">← REGRAS</a></header><section class="hero"><span class="eyebrow">MYTHØS · REGULAMENTO OFICIAL</span><h1>Regras da Polícia 👮</h1><p id="meta">Carregando regulamento...</p></section><section id="rules"></section><footer class="footer">MYTHØS NETWORK • <a class="back" href="/regras.html">Voltar para a Central</a></footer></main><script>(async()=>{try{const r=await fetch('/api/rules',{cache:'no-store'}),j=await r.json();const s=(j.rules||[]).find(x=>/pol[ií]cia|police/i.test(String(x.title||'')));if(!s)throw new Error('Regra não encontrada');document.getElementById('meta').innerHTML='<span style="color:#16def4;font-weight:900">'+s.items.length+' itens</span> · conteúdo integral desta seção.';document.getElementById('rules').innerHTML=s.items.map((x,k)=>'<article class="embed"><div class="embedNo">ITEM '+String(k+1).padStart(3,'0')+'</div><div class="embedText">'+String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))+'</div></article>').join('')}catch(e){document.getElementById('meta').textContent='Não foi possível carregar as regras.'}})();</script></body></html>';
fs.writeFileSync(path.join(dist,'regras-policia.html'),html);
const index=path.join(dist,'regras.html');
if(fs.existsSync(index)){let s=fs.readFileSync(index,'utf8');if(!s.includes('/regras-policia.html')){const link='<a class="link" href="/regras-policia.html"><strong>POLÍCIA 👮</strong><span>Regulamento completo · Abrir página →</span></a>';s=s.replace('</div><footer class="footer">',link+'</div><footer class="footer">');fs.writeFileSync(index,s)}}
console.log('Police rules page generated.');
