const fs=require('fs');
const path=require('path');
const f=path.join(__dirname,'dist','admin.html');
if(!fs.existsSync(f))throw new Error('dist/admin.html não encontrado');
let h=fs.readFileSync(f,'utf8');

const css=`<style id="mythos-ponto-style">
.pointBox{border:1px solid #34214d;border-radius:18px;background:linear-gradient(145deg,#110a19,#08070d);padding:18px;margin:12px 0;box-shadow:0 12px 36px #0007}.pointHero{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center}.pointStatus{font-size:27px;font-weight:950;margin:8px 0}.pointOpen{color:#4fffd0}.pointClosed{color:#ff769f}.pointClock{font-size:12px;color:#a99db2}.pointActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.pointGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pointTableWrap{overflow:auto;border:1px solid #2b2038;border-radius:14px}.pointTable{width:100%;min-width:620px;border-collapse:collapse;font-size:12px}.pointTable th{background:#130b22;color:#cdbbd8;font-size:10px;letter-spacing:1px;text-transform:uppercase}.pointTable th,.pointTable td{padding:11px;border-bottom:1px solid #241a30;text-align:left}.pointTable tr:last-child td{border-bottom:0}.pointBadge{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:900}.pointBadge.open{color:#4fffd0;background:#063126;border:1px solid #155d4b}.pointBadge.closed{color:#ff9ab8;background:#2a0b18;border:1px solid #6c2340}.approve{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.pending{color:#ffd36b}.approved{color:#4fffd0}.rejected{color:#ff769f}.pointError{padding:13px;border:1px solid #6a2944;border-radius:12px;background:#180a13;color:#ff9dbb;font-size:12px;line-height:1.5}.pointEmpty{padding:18px;color:#888;text-align:center}.pointSub{color:#9f91ab;font-size:12px;line-height:1.6}.pointTitleRow{display:flex;justify-content:space-between;align-items:center;gap:12px}.pointRefresh{border:1px solid #4a2b66;border-radius:10px;padding:9px 12px;background:#12091a;color:#d7a5ff;font-weight:900;cursor:pointer}.pointForm{display:grid;grid-template-columns:180px 1fr;gap:10px;align-items:end;margin-top:12px}.pointForm textarea,.pointForm input{width:100%;padding:11px;background:#09050e;border:1px solid #4a235d;border-radius:10px;color:#fff;outline:none}.pointForm textarea{min-height:44px;resize:vertical}.pointReport{line-height:1.8;color:#c9bfd0}.pointReport b{color:#fff}@media(max-width:700px){.pointHero,.pointGrid{grid-template-columns:1fr}.pointForm{grid-template-columns:1fr}.pointStatus{font-size:23px}}
</style>`;

const js=`<script id="mythos-ponto-script">(()=>{
const APPROVERS=['owner','staff','all','manager','admin_lider','admin_2','sublider','admin','developer'];
const POINT=[...APPROVERS,'suporte','admin_assistente','atendimento'];
const token=()=>localStorage.getItem('mythos_admin_token')||'';
const auth=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let busy=false;
async function api(url,options={}){const r=await fetch(url,{...options,cache:'no-store'});const j=await r.json().catch(()=>({error:'Resposta inválida do servidor.'}));if(!r.ok)throw Error(j.error||('Erro HTTP '+r.status));return j}
function role(){return String(window.__role||window.__mythosRole||'').toLowerCase()}
function hasApproval(){return APPROVERS.includes(role())}
function setError(message){const safe=esc(message);['pointCurrent','pointEntries','pointJust','pointReport'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML='<div class="pointError">Falha ao carregar o cartão ponto: '+safe+'</div>'})}
function renderCurrent(current){const el=document.getElementById('pointCurrent');if(!el)return;el.innerHTML=current?'<div class="pointHero"><div><div class="pointStatus pointOpen">PONTO ABERTO</div><div class="pointClock">Entrada: '+esc(current.opened_display||current.opened_at)+' · Brasília</div></div><div class="pointActions"><button class="btn" onclick="pointAction(\'close\')">REGISTRAR SAÍDA</button></div></div>':'<div class="pointHero"><div><div class="pointStatus pointClosed">PONTO FECHADO</div><div class="pointClock">Nenhum ponto aberto no momento.</div></div><div class="pointActions"><button class="btn" onclick="pointAction(\'open\')">REGISTRAR ENTRADA</button></div></div>'}
function renderEntries(entries){const el=document.getElementById('pointEntries');if(!el)return;const rows=(entries||[]).map((x,i)=>'<tr><td>'+String(i+1)+'</td><td><b>'+esc(x.name)+'</b><br><small>'+esc(x.email||'')+'</small></td><td>'+esc(x.opened_display||x.opened_at)+'</td><td>'+esc(x.closed_display||x.closed_at||'Aberto')+'</td><td><span class="pointBadge '+(x.status==='open'?'open':'closed')+'">'+(x.status==='open'?'ABERTO':'FECHADO')+'</span></td><td>'+Number(x.hours||0).toFixed(2)+'h</td></tr>').join('');el.innerHTML='<div class="pointTableWrap"><table class="pointTable"><thead><tr><th>#</th><th>COLABORADOR</th><th>ENTRADA</th><th>SAÍDA</th><th>STATUS</th><th>HORAS</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6"><div class="pointEmpty">Nenhum registro encontrado.</div></td></tr>')+'</tbody></table></div>'}
function renderJust(just){const el=document.getElementById('pointJust');if(!el)return;const oldDate=document.getElementById('justDate')?.value||'';const oldReason=document.getElementById('justReason')?.value||'';const cards=(just||[]).map(x=>'<div class="pointBox"><b>'+esc(x.name)+'</b> · '+esc(x.date)+'<br><span class="pointSub">'+esc(x.reason)+'</span><br><span class="'+esc(x.status)+'">'+esc(x.status==='pending'?'PENDENTE':x.status==='approved'?'APROVADA':'RECUSADA')+'</span>'+(x.reviewed_by?' · '+esc(x.reviewed_by.name):'')+(hasApproval()&&x.status==='pending'?'<div class="approve"><button class="btn" onclick="reviewJust(\''+esc(x.id)+'\',\'approved\')">APROVAR</button><button class="btn alt" onclick="reviewJust(\''+esc(x.id)+'\',\'rejected\')">RECUSAR</button></div>':'')+'</div>').join('');el.innerHTML='<div class="pointForm"><div><label>DATA</label><input id="justDate" type="date" value="'+esc(oldDate)+'"></div><div><label>MOTIVO</label><textarea id="justReason" placeholder="Informe o motivo da justificativa">'+esc(oldReason)+'</textarea></div></div><div class="pointActions"><button class="btn" onclick="pointJustify()">ENVIAR JUSTIFICATIVA</button></div>'+(cards||'<div class="pointEmpty">Nenhuma justificativa encontrada.</div>')}
async function loadReport(){const el=document.getElementById('pointReport');if(!el||!hasApproval())return;try{const j=await api('/api/ponto',{method:'POST',headers:auth(),body:JSON.stringify({action:'report'})});el.innerHTML='<div class="pointReport"><b>Relatório geral</b><br>'+Number(j.totalHours||0).toFixed(2)+' horas · '+Number(j.entries||0)+' registros<br>'+Object.entries(j.byRole||{}).map(([k,v])=>esc(k)+': '+Number(v||0).toFixed(2)+'h').join(' · ')+'</div>'}catch(e){el.innerHTML='<div class="pointError">Falha no relatório: '+esc(e.message||e)+'</div>'}}
async function load(){if(busy||!token())return;const point=document.getElementById('point');if(!point)return;busy=true;try{const me=await api('/api/auth?action=me',{headers:auth()});const r=String(me.user?.role||'').toLowerCase();window.__role=r;window.__mythosRole=r;if(!POINT.includes(r))throw Error('Seu cargo não possui acesso ao Cartão Ponto.');const j=await api('/api/ponto',{headers:auth()});renderCurrent(j.current);renderEntries(j.entries);renderJust(j.justifications);await loadReport()}catch(e){setError(e.message||e)}finally{busy=false}}
window.pointAction=async a=>{try{await api('/api/ponto',{method:'POST',headers:auth(),body:JSON.stringify({action:a})});await load()}catch(e){alert(e.message||e)}};
window.pointJustify=async()=>{try{const date=document.getElementById('justDate')?.value||'',reason=document.getElementById('justReason')?.value||'';await api('/api/ponto',{method:'POST',headers:auth(),body:JSON.stringify({action:'justify',date,reason})});await load()}catch(e){alert(e.message||e)}};
window.reviewJust=async(id,status)=>{try{await api('/api/ponto',{method:'POST',headers:auth(),body:JSON.stringify({action:'review',id,status})});await load()}catch(e){alert(e.message||e)}};
window.mythosPointRefresh=load;
const oldTab=window.tab;window.tab=function(id,el){if(typeof oldTab==='function')oldTab(id,el);if(id==='point')setTimeout(load,80)};
function bind(){document.querySelectorAll('.tab').forEach(el=>{if(el.dataset.mythosPointBound)return;el.dataset.mythosPointBound='1';el.addEventListener('click',()=>{if((el.textContent||'').toUpperCase().includes('CARTÃO PONTO'))setTimeout(load,80)})});const p=document.getElementById('point');if(p?.classList.contains('active'))setTimeout(load,80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();window.addEventListener('load',bind);setTimeout(bind,500);setTimeout(bind,1500);
})();</script>`;

if(!h.includes('mythos-ponto-style'))h=h.replace('</head>',css+'</head>');
const pointPanel='<section id="point" class="panel"><div class="box"><div class="pointTitleRow"><div><h2>CARTÃO PONTO</h2><div class="muted">Horário padrão de Brasília — America/Sao_Paulo.</div></div><button class="pointRefresh" onclick="mythosPointRefresh()">ATUALIZAR</button></div><div id="pointCurrent" class="pointBox">Carregando...</div><div class="pointGrid"><div class="pointBox"><h3>LOGS DOS PONTOS</h3><div class="pointSub">Entradas e saídas registradas.</div><div id="pointEntries">Carregando...</div></div><div class="pointBox"><h3>JUSTIFICATIVAS</h3><div class="pointSub">Data + motivo. Um responsável poderá aprovar ou recusar.</div><div id="pointJust">Carregando...</div></div></div><div class="pointBox"><h3>RELATÓRIOS DE PONTO</h3><div class="pointSub">Relatórios para liderança, Manager, ALL, Staff e Owner.</div><div id="pointReport">Carregando...</div></div></div></section>';
h=h.replace(/<section id="point" class="panel">[\s\S]*?<\/section>/,pointPanel);
h=h.replace(/<script id="mythos-ponto-script">[\s\S]*?<\/script>/g,'');
h=h.replace('</body>',js+'</body>');
fs.writeFileSync(f,h);
console.log('Ponto panel generated and runtime hardened.');
