import type {VercelRequest,VercelResponse} from '@vercel/node';
import crypto from 'node:crypto';
import{readDB,writeDB,passwordHash,passwordOk,signSession,currentUser,publicUser,addLog}from'./_github';
const MASTER='quenidyyonline.17@gmail.com';
const meta=(req:any)=>({ip:String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'desconhecido').split(',')[0].trim(),userAgent:String(req.headers['user-agent']||'').slice(0,300)});
export default async function handler(req:VercelRequest,res:VercelResponse){try{const{db,sha}=await readDB();const action=String(req.query.action||'');if(req.method==='GET'&&action==='me'){const u=currentUser(req,db);return res.status(200).json({user:u?publicUser(u):null});}if(req.method!=='POST')return res.status(405).json({error:'Método não permitido'});const b:any=req.body||{};
if(action==='signup'){const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),displayName=String(b.displayName||email.split('@')[0]).trim();if(!email.includes('@')||password.length<6)return res.status(400).json({error:'Informe e-mail válido e senha com pelo menos 6 caracteres.'});if(db.users.some(u=>u.email===email))return res.status(409).json({error:'Este e-mail já está cadastrado.'});const hp=passwordHash(password);const u={id:crypto.randomUUID(),email,username:displayName.replace(/\s+/g,'_').slice(0,24),display_name:displayName,avatar_url:null,role:email===MASTER?'admin':'player',created_at:new Date().toISOString(),passwordHash:hp.hash,passwordSalt:hp.salt};db.users.push(u);addLog(db,{type:'signup',email,display_name:displayName,...meta(req)});await writeDB(db,sha,`site: novo usuário ${email}`);return res.status(201).json({token:signSession(u.id),user:publicUser(u)});}
if(action==='login'){const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),u=db.users.find(x=>x.email===email);if(!u||!passwordOk(password,u.passwordHash,u.passwordSalt))return res.status(401).json({error:'E-mail ou senha incorretos.'});addLog(db,{type:'login',email:u.email,display_name:u.display_name,role:u.role,...meta(req)});await writeDB(db,sha,`auth: login ${u.email}`);return res.status(200).json({token:signSession(u.id),user:publicUser(u)});}
if(action==='profile'){const u=currentUser(req,db);if(!u)return res.status(401).json({error:'Sessão inválida.'});const avatar=b.avatar_url===null?null:String(b.avatar_url||'');if(avatar.length>2800000)return res.status(413).json({error:'Imagem muito grande.'});u.avatar_url=avatar;u.display_name=String(b.display_name||u.display_name).slice(0,60);u.username=String(b.username||u.username).slice(0,32);await writeDB(db,sha,`site: atualizar perfil ${u.email}`);return res.status(200).json({user:publicUser(u)});}
return res.status(400).json({error:'Ação inválida.'});}catch(e:any){return res.status(500).json({error:e.message||'Erro interno'});}}
