import type { VercelRequest,VercelResponse } from '@vercel/node';
import crypto from 'node:crypto';
import {readDB,writeDB,currentUser,addLog} from './_github';
const APPROVERS=['owner','staff','all','manager'];
const STAFF=['owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','admin_assistente','atendimento'];
const meta=(req:any)=>({ip:String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'desconhecido').split(',')[0].trim(),userAgent:String(req.headers['user-agent']||'').slice(0,300)});
export default async function handler(req:VercelRequest,res:VercelResponse){try{const {db,sha}=await readDB();db.candidates=db.candidates||[];db.admin_data=db.admin_data||[];const u=currentUser(req,db);if(!u||!STAFF.includes(u.role))return res.status(403).json({error:'Sem permissão.'});
if(req.method==='GET')return res.status(200).json({candidates:db.candidates});
if(req.method!=='POST'&&req.method!=='PATCH')return res.status(405).json({error:'Método não permitido'});
const b:any=req.body||{};
if(req.method==='POST'){if(!b.candidato?.trim()||!b.nome_real?.trim()||!b.nome_jogo?.trim())return res.status(400).json({error:'Preencha candidato, nome real e nome em jogo.'});const c={id:crypto.randomUUID(),status:'pendente',created_at:new Date().toISOString(),created_by:u.email,created_by_name:u.display_name,...b};db.candidates.unshift(c);addLog(db,{type:'candidate_create',email:u.email,display_name:u.display_name,role:u.role,candidate:c.candidato,...meta(req)});await writeDB(db,sha,`candidatos: novo candidato ${c.candidato}`);return res.status(201).json({candidate:c});}
const c=db.candidates.find((x:any)=>x.id===b.id);if(!c)return res.status(404).json({error:'Candidato não encontrado.'});if(!APPROVERS.includes(u.role))return res.status(403).json({error:'Somente Owner, Staff, ALL ou Manager aprovam candidatos.'});if(!['aprovar','rejeitar'].includes(b.action))return res.status(400).json({error:'Ação inválida.'});c.status=b.action==='aprovar'?'aprovado':'rejeitado';c.reviewed_at=new Date().toISOString();c.reviewed_by=u.email;c.reviewed_by_name=u.display_name;c.review_note=String(b.note||'').slice(0,1000);addLog(db,{type:`candidate_${b.action}`,email:u.email,display_name:u.display_name,role:u.role,candidate:c.candidato,...meta(req)});
if(b.action==='aprovar'){const record={id:crypto.randomUUID(),type:'candidato_administracao_suporte',candidate_id:c.id,created_at:new Date().toISOString(),approved_at:c.reviewed_at,approved_by:u.email,approved_by_name:u.display_name,source:'candidatos',data:{nome_admin:c.nome_para_adm||c.nome_adm||c.nome_jogo||'',nome_completo:c.nome_real||'',idade:c.idade||'',servidor_local:c.servidor_adm||c.servidor_local||c.servidor_que_sera_adm||'',discord:c.discord||c.discord_tag||c.at_discord||c.nome_discord||c.link_perfil||c.perfil_link||c.link_do_perfil||'',regras_acertadas:c.regras_acertadas??c.acertou_regras??c.regras_ok??'',video_novo_candidato:c.video_novo_candidato||c.video_link||c.video||c.link_video||c.drive_video||''}};db.admin_data.unshift(record);addLog(db,{type:'admin_data_candidate',email:u.email,display_name:u.display_name,role:u.role,candidate:c.candidato,...meta(req)});}
await writeDB(db,sha,`candidatos: ${b.action} ${c.candidato}`);return res.status(200).json({candidate:c,admin_data_registered:b.action==='aprovar'});}catch(e:any){return res.status(500).json({error:e.message||'Erro interno'});}}