import type { VercelRequest, VercelResponse } from '@vercel/node';
import crypto from 'node:crypto';
import { readDB, writeDB, currentUser, publicUser, OWNER_EMAILS, isOwnerEmail } from './_github';
export const ROLES=['player','owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','admin_assistente','atendimento','admin','developer'];
export const ROLE_LABELS:any={player:'Player',owner:'Owner',staff:'Staff',all:'ALL',manager:'Manager','admin_lider':'Admin Líder','admin_2':'Admin ²',sublider:'Sublíder',suporte:'Suporte','admin_assistente':'Admin Assistente',atendimento:'Atendimento',admin:'Admin',developer:'Developer'};
export const PERMISSIONS:any={owner:['all'],staff:['all'],all:['all'],manager:['logs','audit','point','justification'],admin_lider:['logs','point','justification'],admin_2:['point','justification'],sublider:['point','justification'],suporte:['tickets','point','justification'],admin_assistente:['point','justification'],atendimento:['tickets','point','justification'],admin:['tickets','point','justification'],developer:['logs','audit','point','justification'],player:[]};
const effective=(u:any)=>isOwnerEmail(u?.email)?{...u,role:'owner'}:u;
const has=(u:any,p:string)=>{const e=effective(u);return !!e&&(isOwnerEmail(e.email)||['owner','staff','all'].includes(e.role)||(PERMISSIONS[e.role]||[]).includes('all')||(PERMISSIONS[e.role]||[]).includes(p));};
const staff=(u:any)=>has(u,'tickets');
const canManageRoles=(u:any)=>{const e=effective(u);return !!e&&(isOwnerEmail(e.email)||['owner','staff','all'].includes(e.role));};
const canGrantOwner=(u:any)=>!!u&&isOwnerEmail(u.email);
export const roleLabel=(r:string)=>ROLE_LABELS[r]||r;
export default async function handler(req:VercelRequest,res:VercelResponse){try{const {db,sha}=await readDB();const u=currentUser(req,db);const table=String(req.query.table||'');const b:any=req.body||{};
if(req.method==='GET'){
 if(table==='stats')return res.json({count:db.users.length});
 if(table==='users'){if(!canManageRoles(u))return res.status(403).json({error:'Acesso negado'});return res.json({users:db.users.map(x=>publicUser(effective(x))),count:db.users.length,roles:ROLES,roleLabels:ROLE_LABELS,permissions:PERMISSIONS});}
 if(table==='logs'){if(!has(u,'logs'))return res.status(403).json({error:'Acesso negado'});return res.json({logs:(db.logs||[]).slice(0,500)});}
 if(table==='notifications'){if(!u)return res.status(401).json({error:'Sessão inválida'});return res.json(db.notifications.filter(n=>n.user_id===u.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,50));}
 if(table==='tickets'){if(!u)return res.status(401).json({error:'Sessão inválida'});return res.json((staff(u)?db.tickets:db.tickets.filter(t=>t.user_id===u.id)).sort((a,b)=>b.created_at.localeCompare(a.created_at)));}
}
if(table==='users'&&req.method==='PATCH'){if(!canManageRoles(u))return res.status(403).json({error:'Somente Owner, Staff ou ALL podem gerenciar cargos'});const t=db.users.find(x=>x.id===b.id);if(!t)return res.status(404).json({error:'Usuário não encontrado'});if(isOwnerEmail(t.email))return res.status(403).json({error:'Owner protegido'});if(!ROLES.includes(b.role))return res.status(400).json({error:'Cargo inválido'});if(b.role==='owner'&&!canGrantOwner(u))return res.status(403).json({error:'Somente Owner pode conceder o cargo de Owner'});t.role=b.role;db.logs=db.logs||[];db.logs.unshift({id:crypto.randomUUID(),type:'role_change',email:u.email,display_name:u.display_name,target:t.email,role:b.role,role_label:roleLabel(b.role),created_at:new Date().toISOString()});await writeDB(db,sha,'admin: alterar cargo');return res.json({user:publicUser(effective(t))});}
if(table==='notifications'&&req.method==='PATCH'){if(!u)return res.status(401).json({error:'Sessão inválida'});db.notifications.filter(n=>n.user_id===u.id).forEach(n=>n.read=true);await writeDB(db,sha,'site: ler notificações');return res.json({ok:true});}
if(table==='tickets'&&req.method==='POST'){if(!u)return res.status(401).json({error:'Faça login com seu e-mail e senha para abrir um ticket'});const action=String(b.action||'create');let t=db.tickets.find(x=>x.id===b.id);if(action==='create'){t={id:crypto.randomUUID(),user_id:u.id,user_name:u.display_name,category:String(b.category||'Suporte'),subject:String(b.subject||'Ticket'),message:String(b.message||''),status:'open',assigned_to:null,replies:[],created_at:new Date().toISOString(),updated_at:new Date().toISOString()};db.tickets.push(t);}else{if(!t)return res.status(404).json({error:'Ticket não encontrado'});if(!staff(u))return res.status(403).json({error:'Somente Suporte, Atendimento ou cargos administrativos com permissão podem atender tickets'});if(action==='reply'){const now=new Date().toISOString();t.replies.push({id:crypto.randomUUID(),user_id:u.id,user_name:u.display_name,role:u.role,message:String(b.message||''),created_at:now});t.status='in_progress';t.assigned_to=u.id;t.updated_at=now;db.notifications.push({id:crypto.randomUUID(),user_id:t.user_id,type:'ticket_reply',title:'Ticket atendido',body:`${u.display_name} respondeu ao seu ticket.`,ticket_id:t.id,read:false,created_at:now});}if(action==='close'){const now=new Date().toISOString();t.status='closed';t.assigned_to=u.id;t.updated_at=now;db.notifications.push({id:crypto.randomUUID(),user_id:t.user_id,type:'ticket_closed',title:'Ticket fechado',body:`Seu ticket foi fechado por ${u.display_name}.`,ticket_id:t.id,read:false,created_at:now});}}await writeDB(db,sha,`site: ticket ${action}`);return res.json({ticket:t});}
return res.status(400).json({error:'Requisição inválida'});}catch(e:any){return res.status(500).json({error:e.message||'Erro interno'});}}
