import type { VercelRequest,VercelResponse } from '@vercel/node';
import crypto from 'node:crypto';
import { readDB,writeDB,currentUser,addLog } from './_github';
const POINT=['owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','admin_assistente','atendimento','admin','developer'];
const APPROVERS=['owner','staff','all','manager','admin_lider','admin_2','sublider','admin','developer'];
const can=(u:any,list:string[])=>!!u&&list.includes(String(u.role));
const br=(iso:string)=>new Date(iso).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'medium'});
const meta=(req:any)=>({ip:String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'desconhecido').split(',')[0].trim(),userAgent:String(req.headers['user-agent']||'').slice(0,300)});
export default async function handler(req:VercelRequest,res:VercelResponse){try{
 const {db,sha}=await readDB();db.pointEntries=db.pointEntries||[];db.justifications=db.justifications||[];const u=currentUser(req,db);if(!u)return res.status(401).json({error:'Sessão inválida. Faça login novamente.'});
 if(req.method==='GET'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso ao cartão ponto para o cargo '+String(u.role)+'.'});const mine=db.pointEntries.filter((x:any)=>x.user_id===u.id).sort((a:any,b:any)=>String(b.opened_at).localeCompare(String(a.opened_at)));const reports=can(u,APPROVERS)?db.pointEntries.slice().sort((a:any,b:any)=>String(b.opened_at).localeCompare(String(a.opened_at))):mine;const just=can(u,APPROVERS)?db.justifications.slice().sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at))):db.justifications.filter((x:any)=>x.user_id===u.id).sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at)));return res.json({ok:true,role:u.role,canReport:can(u,APPROVERS),current:db.pointEntries.find((x:any)=>x.user_id===u.id&&x.status==='open')||null,entries:reports.map((x:any)=>({...x,opened_display:br(x.opened_at),closed_display:x.closed_at?br(x.closed_at):null})),justifications:just});}
 if(req.method!=='POST')return res.status(405).json({error:'Método não permitido'});const b:any=req.body||{},action=String(b.action||'');
 if(action==='open'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso ao cartão ponto.'});if(db.pointEntries.some((x:any)=>x.user_id===u.id&&x.status==='open'))return res.status(409).json({error:'Você já possui um ponto aberto.'});const opened=new Date().toISOString();const e={id:crypto.randomUUID(),user_id:u.id,name:u.display_name,email:u.email,role:u.role,opened_at:opened,opened_display:br(opened),closed_at:null,closed_display:null,hours:0,status:'open'};db.pointEntries.push(e);addLog(db,{type:'point_open',email:u.email,display_name:u.display_name,role:u.role,...meta(req)});await writeDB(db,sha,'ponto: abrir');return res.status(201).json({ok:true,entry:e});}
 if(action==='close'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso ao cartão ponto.'});const e=db.pointEntries.find((x:any)=>x.user_id===u.id&&x.status==='open');if(!e)return res.status(404).json({error:'Nenhum ponto aberto.'});const closed=new Date();e.closed_at=closed.toISOString();e.closed_display=br(e.closed_at);e.hours=Math.max(0,(closed.getTime()-new Date(e.opened_at).getTime())/3600000);e.status='closed';addLog(db,{type:'point_close',email:u.email,display_name:u.display_name,role:u.role,hours:e.hours,...meta(req)});await writeDB(db,sha,'ponto: fechar');return res.json({ok:true,entry:e});}
 if(action==='justify'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso às justificativas.'});const date=String(b.date||'').slice(0,10),reason=String(b.reason||'').trim().slice(0,2000);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!reason)return res.status(400).json({error:'Informe Data e Motivo.'});const j={id:crypto.randomUUID(),user_id:u.id,name:u.display_name,email:u.email,role:u.role,date,reason,status:'pending',created_at:new Date().toISOString(),reviewed_at:null,reviewed_by:null};db.justifications.push(j);addLog(db,{type:'justification_create',email:u.email,display_name:u.display_name,date,...meta(req)});await writeDB(db,sha,'ponto: justificar');return res.status(201).json({ok:true,justification:j});}
 if(action==='review'){if(!can(u,APPROVERS))return res.status(403).json({error:'Sem permissão para aprovar justificativas.'});const j=db.justifications.find((x:any)=>x.id===b.id);if(!j)return res.status(404).json({error:'Justificativa não encontrada.'});const status=b.status==='approved'?'approved':b.status==='rejected'?'rejected':'';if(!status)return res.status(400).json({error:'Decisão inválida.'});j.status=status;j.reviewed_at=new Date().toISOString();j.reviewed_by={id:u.id,name:u.display_name,email:u.email,role:u.role};addLog(db,{type:`justification_${status}`,email:u.email,display_name:u.display_name,target:j.email,justification:j.id,...meta(req)});await writeDB(db,sha,`ponto: justificativa ${status}`);return res.json({ok:true,justification:j});}
 if(action==='report'){if(!can(u,APPROVERS))return res.status(403).json({error:'Sem permissão para relatórios.'});const entries=db.pointEntries.filter((x:any)=>x.status==='closed');const total=entries.reduce((s:number,x:any)=>s+Number(x.hours||0),0);const byRole:any={};for(const x of entries)byRole[x.role]=(byRole[x.role]||0)+Number(x.hours||0);return res.json({ok:true,totalHours:total,entries:entries.length,byRole});}
 return res.status(400).json({error:'Ação inválida'});
}catch(e:any){return res.status(500).json({error:e.message||'Erro interno no cartão ponto'});}}
