import type { VercelRequest,VercelResponse } from '@vercel/node';
import crypto from 'node:crypto';
import { readDB,writeDB,currentUser,addLog } from './_github';
const FULL=['owner','staff','all','admin','developer'];
const POINT=['owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','atendimento','admin','developer'];
const APPROVERS=['owner','staff','all','manager','admin_lider','admin_2','sublider','admin','developer'];
const meta=(req:any)=>({ip:String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'desconhecido').split(',')[0].trim(),userAgent:String(req.headers['user-agent']||'').slice(0,300)});
const can=(u:any,list:string[])=>!!u&&list.includes(String(u.role));
const nowBR=()=>new Date().toLocaleString('sv-SE',{timeZone:'America/Sao_Paulo',hour12:false}).replace(' ','T');
export default async function handler(req:VercelRequest,res:VercelResponse){try{const {db,sha}=await readDB();db.pointEntries=db.pointEntries||[];db.justifications=db.justifications||[];const u=currentUser(req,db);if(!u)return res.status(401).json({error:'Sessão inválida.'});
if(req.method==='GET'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso ao cartão ponto.'});const mine=db.pointEntries.filter((x:any)=>x.user_id===u.id).sort((a:any,b:any)=>b.opened_at.localeCompare(a.opened_at));const reports=can(u,APPROVERS)?db.pointEntries.slice().sort((a:any,b:any)=>b.opened_at.localeCompare(a.opened_at)):mine;const just=can(u,APPROVERS)?db.justifications.slice().sort((a:any,b:any)=>b.created_at.localeCompare(a.created_at)):db.justifications.filter((x:any)=>x.user_id===u.id).sort((a:any,b:any)=>b.created_at.localeCompare(a.created_at));return res.json({current:db.pointEntries.find((x:any)=>x.user_id===u.id&&x.status==='open')||null,entries:reports,justifications:just});}
if(req.method!=='POST')return res.status(405).json({error:'Método não permitido'});const b:any=req.body||{},action=String(b.action||'');
if(action==='open'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso ao cartão ponto.'});if(db.pointEntries.some((x:any)=>x.user_id===u.id&&x.status==='open'))return res.status(409).json({error:'Você já possui um ponto aberto.'});const e={id:crypto.randomUUID(),user_id:u.id,name:u.display_name,email:u.email,role:u.role,opened_at:nowBR(),closed_at:null,hours:0,status:'open'};db.pointEntries.push(e);addLog(db,{type:'point_open',email:u.email,display_name:u.display_name,role:u.role,...meta(req)});await writeDB(db,sha,'ponto: abrir');return res.status(201).json({entry:e});}
if(action==='close'){const e=db.pointEntries.find((x:any)=>x.user_id===u.id&&x.status==='open');if(!e)return res.status(404).json({error:'Nenhum ponto aberto.'});e.closed_at=nowBR();e.hours=Math.max(0,(new Date(e.closed_at).getTime()-new Date(e.opened_at).getTime())/3600000);e.status='closed';addLog(db,{type:'point_close',email:u.email,display_name:u.display_name,role:u.role,hours:e.hours,...meta(req)});await writeDB(db,sha,'ponto: fechar');return res.json({entry:e});}
if(action==='justify'){if(!can(u,POINT))return res.status(403).json({error:'Sem acesso às justificativas.'});const date=String(b.date||'').slice(0,10),reason=String(b.reason||'').trim().slice(0,2000);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!reason)return res.status(400).json({error:'Informe Data e Motivo.'});const j={id:crypto.randomUUID(),user_id:u.id,name:u.display_name,email:u.email,role:u.role,date,reason,status:'pending',created_at:nowBR(),reviewed_at:null,reviewed_by:null};db.justifications.push(j);addLog(db,{type:'justification_create',email:u.email,display_name:u.display_name,date,...meta(req)});await writeDB(db,sha,'ponto: justificar');return res.status(201).json({justification:j});}
if(action==='review'){if(!can(u,APPROVERS))return res.status(403).json({error:'Sem permissão para aprovar justificativas.'});const j=db.justifications.find((x:any)=>x.id===b.id);if(!j)return res.status(404).json({error:'Justificativa não encontrada.'});const status=b.status==='approved'?'approved':b.status==='rejected'?'rejected':'';if(!status)return res.status(400).json({error:'Decisão inválida.'});j.status=status;j.reviewed_at=nowBR();j.reviewed_by={id:u.id,name:u.display_name,email:u.email,role:u.role};addLog(db,{type:`justification_${status}`,email:u.email,display_name:u.display_name,target:j.email,justification:j.id,...meta(req)});await writeDB(db,sha,`ponto: justificativa ${status}`);return res.json({justification:j});}
if(action==='report'){if(!can(u,APPROVERS))return res.status(403).json({error:'Sem permissão para relatórios.'});const entries=db.pointEntries.filter((x:any)=>x.status==='closed');const total=entries.reduce((s:number,x:any)=>s+Number(x.hours||0),0);const byRole:any={};for(const x of entries)byRole[x.role]=(byRole[x.role]||0)+Number(x.hours||0);return res.json({totalHours:total,entries:entries.length,byRole});}
return res.status(400).json({error:'Ação inválida.'});}catch(e:any){return res.status(500).json({error:e.message||'Erro interno'});}}
