import type {VercelRequest,VercelResponse} from '@vercel/node';
import {readDB,writeDB,currentUser} from './_github';
import {MYTHOS_RULES} from '../src/data/mythos-rules';
import {HOSPITAL_RULES} from '../src/data/hospital-rules';
import {POLICE_RULES} from '../src/data/police-rules';
const BIBLE_URL='https://docs.google.com/document/d/1kY_LmtyzU6W7sQeniDjmrT3zIEzGKpuPjeOL17MHTRI/export?format=txt';
function parseBibleText(text:string){const clean=String(text||'').replace(/\s+/g,' ').trim();const top=/(?:>>> )?(\d+)\.\s+\*{3}([^*]+?)\*{3}\s+/g;const hits=[...clean.matchAll(top)];const sections:any[]=[];for(let i=0;i<hits.length;i++){const m=hits[i];const start=(m.index||0)+m[0].length;const end=i+1<hits.length?(hits[i+1].index||clean.length):clean.length;const chunk=clean.slice(start,end).trim();const itemRe=/(?:>>> )?•\s*(\d+\.\d+(?:\s+e\s+\d+\.\d+)?)\s*(?:\|\s*)?/g;const ih=[...chunk.matchAll(itemRe)];const items=ih.map((x,j)=>chunk.slice((x.index||0),j+1<ih.length?(ih[j+1].index||chunk.length):chunk.length).replace(/^(?:>>> )?•\s*/,'').trim()).filter(Boolean);sections.push({number:m[1],title:m[2].trim(),items})}return sections.filter(s=>s.items.length)}
async function remoteRules(){try{const r=await fetch(BIBLE_URL,{cache:'no-store'});if(!r.ok)return null;const rules=parseBibleText(await r.text());return rules.length?rules:null}catch{return null}}
function withDefaultRule(rules:any[],fallback:any,pattern:RegExp){const out=Array.isArray(rules)?rules.map(x=>({...x,items:Array.isArray(x.items)?x.items.slice():[]})):[];const idx=out.findIndex(x=>pattern.test(String(x?.title||'')));if(idx>=0)return out;const nums=out.map(x=>Number(x?.number)).filter(Number.isFinite);const number=String(nums.length?Math.max(...nums)+1:1);return [...out,{number,title:fallback.title,items:fallback.items.slice()}]}
function withOrganizationRules(rules:any[]){return withDefaultRule(withDefaultRule(rules,HOSPITAL_RULES,/hospital|m[eé]dicos?/i),POLICE_RULES,/pol[ií]cia|police/i)}
export default async function handler(req:VercelRequest,res:VercelResponse){try{const {db,sha}=await readDB();const saved=(db as any).rules;if(req.method==='GET'){const remote=await remoteRules();const base=Array.isArray(saved)?saved:(remote||MYTHOS_RULES);return res.status(200).json({rules:withOrganizationRules(base),source:Array.isArray(saved)?'admin':'document'});}const user=currentUser(req,db);if(!user||user.role!=='admin')return res.status(403).json({error:'Acesso restrito ao administrador.'});if(req.method!=='POST')return res.status(405).json({error:'Método não permitido'});const rules=(req.body as any)?.rules;if(!Array.isArray(rules)||!rules.length)return res.status(400).json({error:'Informe pelo menos uma seção.'});for(const s of rules){if(!s||typeof s.number!=='string'||typeof s.title!=='string'||!Array.isArray(s.items)||s.items.length>500)return res.status(400).json({error:'Estrutura de regras inválida.'});if(s.title.length>300||s.number.length>30)return res.status(400).json({error:'Título ou número muito grande.'});for(const item of s.items)if(typeof item!=='string'||item.length>5000)return res.status(400).json({error:'Existe uma regra inválida ou muito grande.'});}(db as any).rules=withOrganizationRules(rules).map((s:any)=>({number:String(s.number).trim(),title:String(s.title).trim(),items:s.items.map((x:any)=>String(x).trim()).filter(Boolean)}));await writeDB(db,sha,'admin: atualizar regras pelo painel');return res.status(200).json({rules:(db as any).rules,source:'admin'});}catch(e:any){return res.status(500).json({error:e.message||'Erro interno'});}}
