import type {VercelRequest,VercelResponse} from '@vercel/node';
import {readDB,writeDB,currentUser} from './_github';
import {MYTHOS_RULES} from '../src/data/mythos-rules';
import {HOSPITAL_RULES} from '../src/data/hospital-rules';
import {POLICE_RULES} from '../src/data/police-rules';
const BIBLE_URL='https://docs.google.com/document/d/1kY_LmtyzU6W7sQeniDjmrT3zIEzGKpuPjeOL17MHTRI/export?format=txt';
const STAFF=['owner','staff','all','manager','admin_lider','admin_2','sublider','suporte','admin_assistente','atendimento'];
const APPROVERS=['owner','staff','all','manager','admin_lider'];
function parseBibleText(text:string){const clean=String(text||'').replace(/\s+/g,' ').trim();const top=/(?:>>> )?(\d+)\.\s+\*{3}([^*]+?)\*{3}\s+/g;const hits=[...clean.matchAll(top)];const sections:any[]=[];for(let i=0;i<hits.length;i++){const m=hits[i];const start=(m.index||0)+m[0].length;const end=i+1<hits.length?(hits[i+1].index||clean.length):clean.length;const chunk=clean.slice(start,end).trim();const itemRe=/(?:>>> )?•\s*(\d+\.\d+(?:\s+e\s+\d+\.\d+)?)\s*(?:\|\s*)?/g;const ih=[...chunk.matchAll(itemRe)];const items=ih.map((x,j)=>chunk.slice((x.index||0),j+1<ih.length?(ih[j+1].index||chunk.length):chunk.length).replace(/^(?:>>> )?•\s*/,'').trim()).filter(Boolean);if(items.length)sections.push({number:m[1],title:m[2].trim(),items})}return sections}
async function remoteRules(){try{const r=await fetch(BIBLE_URL,{cache:'no-store'});if(!r.ok)return null;const rules=parseBibleText(await r.text());return rules.length?rules:null}catch{return null}}
function normalize(rules:any[]){const out:any[]=[];const sectionKeys=new Set<string>();for(const s of Array.isArray(rules)?rules:[]){if(!s||typeof s.title!=='string')continue;const title=s.title.trim();const key=title.toLocaleLowerCase('pt-BR').replace(/\s+/g,' ');if(sectionKeys.has(key))continue;sectionKeys.add(key);const itemKeys=new Set<string>();const items=(Array.isArray(s.items)?s.items:[]).map((x:any)=>String(x).trim()).filter((x:string)=>{const k=x.toLocaleLowerCase('pt-BR').replace(/\s+/g,' ');if(!k||itemKeys.has(k))return false;itemKeys.add(k);return true});if(items.length)out.push({number:String(s.number??'').trim(),title,items})}return out}
function withOrganizationRules(rules:any[]){const out=normalize(rules);const hasHospital=out.some(x=>/hospital|m[eé]dicos?/i.test(x.title));const hasPolice=out.some(x=>/pol[ií]cia|police/i.test(x.title));if(!hasHospital)out.push({number:HOSPITAL_RULES.number,title:HOSPITAL_RULES.title,items:HOSPITAL_RULES.items.slice()});if(!hasPolice)out.push({number:POLICE_RULES.number,title:POLICE_RULES.title,items:POLICE_RULES.items.slice()});return normalize(out)}
export default async function handler(req:VercelRequest,res:VercelResponse){try{const {db,sha}=await readDB();const saved=(db as any).rules;if(req.method==='GET'){const remote=await remoteRules();const base=Array.isArray(saved)?saved:(remote||MYTHOS_RULES);return res.status(200).json({rules:withOrganizationRules(base),source:Array.isArray(saved)?'admin':'document'});}const user=currentUser(req,db);if(!user||!STAFF.includes(String(user.role)))return res.status(403).json({error:'Acesso restrito à equipe autorizada.'});if(req.method!=='POST')return res.status(405).json({error:'Método não permitido'});if(!APPROVERS.includes(String(user.role)))return res.status(403).json({error:'Somente Owner, Staff, ALL, Manager ou Admin Líder podem salvar regras.'});const rules=(req.body as any)?.rules;if(!Array.isArray(rules)||!rules.length)return res.status(400).json({error:'Informe pelo menos uma seção.'});for(const s of rules){if(!s||typeof s.number!=='string'||typeof s.title!=='string'||!Array.isArray(s.items)||s.items.length>500)return res.status(400).json({error:'Estrutura de regras inválida.'});if(s.title.length>300||s.number.length>30)return res.status(400).json({error:'Título ou número muito grande.'});for(const item of s.items)if(typeof item!=='string'||item.length>5000)return res.status(400).json({error:'Existe uma regra inválida ou muito grande.'});}(db as any).rules=withOrganizationRules(rules);await writeDB(db,sha,'admin: atualizar regras sem duplicatas');return res.status(200).json({rules:(db as any).rules,source:'admin'});}catch(e:any){return res.status(500).json({error:e.message||'Erro interno'});}}
